Repository aemsites/stericycle-shared, pull requests merged in 2024-11, with the labels that each got.

#429 fix:locations form
  blocks/get-a-quote-form/get-a-quote-form.js
Labels: form

#382 feat: Added support for including form block in a 2 column layout
  blocks/form/form.css
Labels: form

#403 Added styling for campaign form
  blocks/form/form.css
Labels: form

#397 fix:Added fallback for forms in marketing location pages
  blocks/form/form.css
  templates/marketing-location-page/marketing-location-page.js
Labels: form

#509 Fix json-ld
  scripts/scripts.js
Labels: high priority

#513 fix: modal mobile rendering issues
  blocks/modal/modal.css
Labels: forms

#512 fix: prevent scroll position getting reset when modal is opened
  blocks/modal/modal.css
Labels: forms

#508 Issue486: fix forms mobile layout
  blocks/form/form.css
Labels: forms

#517 STERI016-59 Radio button style update
  blocks/form/form.css
  styles/styles.css
Labels: refresh-develop

#463 feat:support to configure multiple modal triggers
  blocks/form/constant.js
  blocks/form/submit.js
  blocks/form/trigger.js
  blocks/modal/modal.js
  scripts/scripts.js
Labels: forms

#532 Fix json-ld & improve security
  scripts/scripts.js
Labels: high priority

#533 STERI016-101: Faq block styles updated
  blocks/faq/faq.css
  styles/styles.css
Labels: refresh-develop

#540 Issue185: pre-fill hidden fields in form
  blocks/form/submit.js
Labels: forms

#550 STERI016-112-button-with-icons-am: Button with icons
  scripts/aem.js
  styles/styles.css
Labels: refresh-develop

#551 STERI016-63-bullets-am: Add Bullet Style
  styles/styles.css
Labels: refresh-develop
