Repository aemsites/stericycle-shared, pull requests merged in 2024-12, with the labels that each got.

#580 STERI016-69-flip-cards-am: Refactor flip-cards block
  blocks/flip-cards/flip-cards.css
  blocks/flip-cards/flip-cards.js
Labels: refresh-develop

#567 fix:allow author to configure form in locations pages
  blocks/form/form.js
  templates/marketing-location-page/marketing-location-page.js
  templates/service-location-page/service-location-page.js
Labels: forms

#559 Steri016 62 ch
  blocks/tabs/default.css
  blocks/tabs/tabs.css
  styles/styles.css
Labels: refresh-develop

#549 Steri016 89 ch
  blocks/hero-banner/hero-banner.css
  blocks/hero-banner/hero-banner.js
  icons/hero-mask.svg
  styles/styles.css
Labels: refresh-develop

#582 STERI016-163-faq-mobile-issue-am: Remove hover styles on mobile
  blocks/faq/faq.css
Labels: bug, refresh-develop

#583 fix: make nav and footer modal configurable
  blocks/footer/footer.js
  blocks/header/alt-2-nav.js
  blocks/header/nav.js
Labels: forms

#584 Steri016 104 ch
  blocks/quote/quote.css
  blocks/quote/quote.js
  styles/styles.css
Labels: refresh-develop

#568 fix:add request a quote button inside header for mobile view
  blocks/hero/hero.css
  blocks/hero/hero.js
  styles/styles.css
Labels: forms

#592 Hero image ch
  blocks/hero-banner/hero-banner.css
  styles/styles.css
Labels: refresh-develop

#572 STERI016-175: Fix form mobile layout
  blocks/form/components/radio/radio.css
  blocks/form/form.css
Labels: bug, refresh-develop

#596 no-ref: Revert page width update
  styles/styles.css
Labels: refresh-develop

#601 no-ref: Add new xxl container token
  blocks/hero-banner/hero-banner.css
  styles/styles.css
Labels: refresh-develop

#600 STERI016-195-input-field-am: Fix inconsistencies in font sizes
  blocks/form/form.css
Labels: bug, refresh-develop

#599 STERI016-147-faq-issue-am: Add margin between sections when options are opened with focus
  blocks/faq/faq.css
Labels: bug, refresh-develop

#594 STERI016-172-buttons-visual-am: Fix Hover Behavior and Icon Arrow Issues
  styles/styles.css
Labels: bug, refresh-develop

#593 STERI016-191-restrict-cards-am: Restrict Flip-Cards to Maximum Four Cards
  blocks/flip-cards/flip-cards.js
Labels: bug, refresh-develop

#603 fix: form styling issues
  blocks/form/form.css
  blocks/modal/modal.css
Labels: forms

#350 feat:added support for user to configure submit success and error messages
  blocks/form/components/wizard/wizard.css
  blocks/form/form.css
  blocks/form/lib/forms-common.js
  blocks/form/lib/transform.js
  blocks/form/lib/util.js
  blocks/form/submit.js
  blocks/get-a-quote-form/get-a-quote-form.css
Labels: forms

#638 STERI016-194-input-issues-am: Input Field - Visual inconsistencies (Color)
  blocks/form/form.css
Labels: bug, refresh-develop

#628 STERI016-129-cards-block-am: Enhance Full-Width Styles for Cards Block
  blocks/cards/cards.css
  blocks/cards/cards.js
  styles/styles.css
Labels: refresh-develop

#644 STERI016-194-input-color-issues-am: Input Field - Visual inconsistencies (Changes)
  blocks/form/form.css
Labels: bug, refresh-develop

#652 Final css
  blocks/form/form.css
Labels: forms

#663 STERI016-127-icon-list-am: Icon List Block (Icon List with Split First Third)
  blocks/icon-list/icon-list.css
Labels: refresh-develop

#653 make submit url relative for stage and prod
  blocks/form/constant.js
Labels: forms

#631 Add blocks dataLayer
  blocks/form/components/wizard/wizard.js
  blocks/form/form.css
  blocks/form/form.js
  blocks/form/submit.js
  blocks/form/utils.js
  blocks/modal/modal.js
  blocks/search/search.js
  blocks/service-location-map/service-location-map.js
  scripts/martech.js
  templates/marketing-location-page/marketing-location-page.js
  templates/service-location-page/service-location-page.js
Labels: analytics

#657 Push page properties to dataLayer
  scripts/martech.js
Labels: analytics

#670 STERI016-47: Cards block - Primary Cards
  blocks/cards/cards.css
  styles/styles.css
Labels: refresh-develop

#671 STERI016-128: Section Block
  styles/styles.css
Labels: refresh-develop

#672 STERI016-59-radio-button-am: Radio Button
  blocks/form/form.css
Labels: refresh-develop

#674 STERI016-245-hero-button-focus-am: Hero - Primary Button
  styles/styles.css
Labels: refresh-develop
