Repository aemsites/stericycle-shared, pull requests merged in 2025-02, with the labels that each got.

#762 STERI016-339: Tabs Block - UAT issue
  blocks/tabs/default.css
Labels: refresh-develop

#760 STERI016-305: Fix mobile alignment and stroke visibility issues.
  blocks/cards/cards.css
Labels: refresh-develop

#757 STERI016-302: Update hero banner styles and form layout with new form…
  blocks/hero-banner/hero-banner.css
  icons/hero-form-graphic.png
  icons/hero-form-graphic.svg
Labels: refresh-develop

#763 STERI016-304: Refactor header padding and remove unnecessary media query
  blocks/header/nav.css
Labels: refresh-develop

#759 Steri016 307 ch
  blocks/columns/default.css
  blocks/header/nav.css
  blocks/header/utils.js
  icons/arrow-left.svg
  scripts/aem.js
Labels: refresh-develop

#758 STERI016-308: Update nav and hero banner CSS styles with correct wrap…
  blocks/header/nav.css
  blocks/hero-banner/hero-banner.css
Labels: refresh-develop

#766 STERI016-85: Refactor OfferBox component with new styling
  blocks/offer-box/offer-box.css
  blocks/offer-box/offer-box.js
  styles/styles.css
Labels: refresh-develop

#770 STERI016-304: Add letter-spacing and text-decoration to header nav
  blocks/header/nav.css
Labels: refresh-develop

#767 STERI016-176: Update CSS styles for columns, form, and offer-box
  blocks/columns/default.js
  blocks/form/form.css
  blocks/offer-box/offer-box.css
  styles/styles.css
Labels: refresh-develop

#773 STERI016-366: Footer - Unable to click on link titles
  blocks/footer/footer.css
  blocks/footer/footer.js
  blocks/footer/utils.js
Labels: refresh-develop

#780 STERI016-300: FAQ - Visual inconsistencies in FAQ
  blocks/faq/faq.css
Labels: refresh-develop

#779 STERI016-387: Update alternate form CSS styles
  blocks/form/components/mask/mask.css
  blocks/form/form.css
  blocks/get-a-quote-form/get-a-quote-form.css
Labels: refresh-develop

#771 STERI016-286: Update hero banner colors and angles
  blocks/hero-banner/hero-banner.css
Labels: refresh-develop

#776 STERI016-321-footer-am: Add Footer short version
  blocks/footer/footer.css
  blocks/footer/footer.js
  blocks/footer/utils.js
Labels: refresh-develop

#777 Steri016 97 ch
  blocks/featuretable/featuretable.css
  blocks/featuretable/featuretable.js
Labels: refresh-develop

#781 STERI016-390: Columns - Padding is removed when another column is added to a section
  blocks/columns/default.css
Labels: refresh-develop

#782 STERI016-299: Add font-style and padding to header nav items
  blocks/header/nav.css
Labels: refresh-develop

#784 STERI016-312: Update wizard form buttons styling
  blocks/form/form.css
Labels: refresh-develop

#785 STERI016-359: Add font size to header nav and adjust padding in conta…
  blocks/header/nav.css
Labels: refresh-develop

#786 STERI016-326: Update hero banner promo badge font size and line height
  blocks/hero-banner/hero-banner.css
Labels: refresh-develop

#783 STERI016-291: Update form.css splitbuttons with flexbox styles
  blocks/form/form.css
Labels: refresh-develop

#787 Steri016 357 ch
  blocks/simple-cta/simple-cta.css
  blocks/simple-cta/simple-cta.js
  scripts/aem.js
  styles/styles.css
Labels: refresh-develop

#790 STERI016-265: Update Notification banner styles
  blocks/banner/banner.css
  blocks/header/nav.css
  blocks/header/utils.js
  styles/styles.css
Labels: refresh-develop

#793 STERI016-229: Update checkboc wizard style
  blocks/form/form.css
Labels: refresh-develop

#792 Steri016 400 ch
  blocks/banner/banner.css
  blocks/header/nav.css
  blocks/header/utils.js
  blocks/service-location-map/service-location-map.js
  icons/distance.svg
  styles/styles.css
Labels: refresh-develop

#791 STERI016-314: Flip Card Tiles - Allow author to choose different CTA button variations
  blocks/flip-cards/flip-cards.css
  blocks/flip-cards/flip-cards.js
Labels: refresh-develop

#798 STERI016-402: Update searchbar spacing
  blocks/header/nav.css
Labels: refresh-develop

#802 STERI016-409: Fix header ctas
  blocks/header/nav.css
  blocks/header/utils.js
Labels: refresh-develop

#797 STERI016-394-flip-card-am: Flip Card - Content on Description Field
  blocks/flip-cards/flip-cards.js
Labels: refresh-develop

#803 STERI016-411: Fix header card alignment
  blocks/offer-box/offer-box.css
Labels: refresh-develop

#804 STERI016-315: Flip Card Tiles - Update the card content to be top aligned
  blocks/flip-cards/flip-cards.css
  blocks/flip-cards/flip-cards.js
  blocks/flip-cards/utils.js
Labels: refresh-develop

#811 STERI016-418: Fix hero banner content width
  blocks/hero-banner/hero-banner.css
Labels: refresh-develop

#810 Prepare go-live analytics
  scripts/delayed.js
  scripts/scripts.js
Labels: high priority, analytics

#816 STERI016-419: Fix columns with form content width
  blocks/form/form.css
  blocks/icon-list/icon-list.css
Labels: refresh-develop

#819 STERI016-396: Header/ Footer Alignment
  blocks/footer/footer.css
  blocks/header/nav.css
Labels: refresh-develop

#821 STERI016-394: Flip Card - Content on Description Field(Bugfix)
  blocks/flip-cards/flip-cards.js
Labels: bug, refresh-develop

#823 STERI016-418: Fix hero banner form content width padding
  blocks/form/form.css
  blocks/hero-banner/hero-banner.css
Labels: refresh-develop

#824 STERI016-409: Fix header icon
  blocks/header/nav.css
Labels: refresh-develop

#827 STERI016-427: Fix table borders
  blocks/featuretable/featuretable.css
  blocks/form/form.css
Labels: refresh-develop

#828 STERI016-355-regression: [Regression] handle problematic utility classes inherited from main code branch
  styles/styles.css
Labels: refresh-develop
