Repository aemsites/stericycle-shared, pull requests merged in 2025-01, with the labels that each got.

#673 STERI016-143-stepper-am: Atom - Stepper
  blocks/form/components/wizard/wizard.css
  blocks/form/components/wizard/wizard.js
Labels: refresh-develop

#676 STERI016-247: Hero Image
  blocks/hero-banner/hero-banner.css
Labels: bug, refresh-develop

#680 STERI016-236 Fix checkbox styling issue on mobile when unchecked
  blocks/form/form.css
Labels: bug, refresh-develop

#682 STERI016-220: Input fields & Buttons are not rendering on Mobile view
  blocks/form/form.css
Labels: bug, refresh-develop

#678 STERI016-246: Adjust hero image layout for tablet screens
  blocks/hero-banner/hero-banner.css
Labels: bug, refresh-develop

#684 STERI016-250: Add gap and flex property to tabs panel div
  blocks/tabs/default.css
Labels: refresh-develop

#675 Steri016 86 - Navigation Header component
  blocks/header/header.js
  blocks/header/nav.css
  blocks/header/nav.js
  blocks/header/utils.js
  icons/arrow-right.svg
  icons/checkpoint.svg
  icons/chevron-right.svg
  icons/close.svg
  icons/magnifying-glass.svg
  icons/phone-ringing-black.svg
  icons/phone-ringing.svg
  styles/styles.css
Labels: refresh-develop

#690 Add cookie button style override
  styles/styles.css
Labels: styling

#687 STERI016-271: Flip-cards block - Inconsistencies in font sizes
  blocks/flip-cards/flip-cards.css
  styles/styles.css
Labels: bug, refresh-develop

#685 STERI016-233: Update quote block styles and add title support
  blocks/quote/quote.css
  blocks/quote/quote.js
  styles/styles.css
Labels: refresh-develop

#700 STERI016-298: Add layout change support
  blocks/header/nav.js
  blocks/header/utils.js
  scripts/scripts.js
Labels: refresh-develop

#702 WIP: add CTA events
  blocks/footer/footer.js
  blocks/post-teaser-list/post-teaser-list.js
  scripts/martech.js
  scripts/scripts.js
Labels: analytics

#712 Add topbar analytics triggers
  blocks/banner/banner.js
Labels: analytics

#713 STERI016-87: Footer block
  blocks/footer/constants.js
  blocks/footer/footer.css
  blocks/footer/footer.js
  blocks/footer/utils.js
Labels: refresh-develop

#686 STERI016-278: Cards block Issue
  blocks/cards/cards.js
Labels: bug, refresh-develop

#730 STERI016-177: Add eyebrow styling to flip cards
  blocks/flip-cards/flip-cards.css
  blocks/flip-cards/flip-cards.js
Labels: refresh-develop

#728 STERI016-252: Remove redundant CSS rule for list-style-bullets
  styles/styles.css
Labels: refresh-develop

#731 Steri016 299 ch
  blocks/header/nav.css
Labels: refresh-develop

#735 Switch to localized query-index
  blocks/blog-filter/blog-filter.js
  blocks/breadcrumb/breadcrumb.js
  blocks/facet-list/facet-list.js
  blocks/paginated-list/paginated-list.js
  blocks/service-location-list/service-location-list.js
  blocks/service-location-map/service-location-map.js
  scripts/scripts.js
Labels: high priority

#740 Hotfix: Update references manually fetching the query-index
  blocks/flip-cards/flip-cards.js
  blocks/search/search.js
Labels: high priority

#744 STERI016-127: Icon List Block(Mobile number styles)
  blocks/icon-list/icon-list.css
Labels: bug, refresh-develop

#743 STERI016-327: Section Block - UAT issues
  blocks/icon-list/icon-list.css
Labels: bug, refresh-develop

#734 Steri016 310 Header - [Get in touch] Inconsistencies in font size and color
  blocks/header/nav.css
Labels: refresh-develop

#733 STERI016-301: Add margin and max-width to search form in header nav
  blocks/header/nav.css
Labels: refresh-develop

#716 Steri016 72 ch
  blocks/facet-list/facet-list.css
  blocks/facet-list/facet-list.js
  blocks/post-teaser-list/post-teaser-list.css
  blocks/post-teaser-list/post-teaser-list.js
  scripts/aem.js
  scripts/scripts.js
  styles/styles.css
Labels: LHS, refresh-develop

#711 STERI016-165: Update styles.css with padding and alignment changes
  styles/styles.css
Labels: LHS, refresh-develop

#739 fix: email regex validation
  blocks/form/constant.js
Labels: forms

#747 STERI016-306: Refactor contact modal title style in header
  blocks/header/nav.css
Labels: refresh-develop

#748 fix: exclude hidden fields from validation during submission
  blocks/form/lib/forms-common.js
Labels: forms

#756 fix: Fix eyebrow link check in flip-cards.js
  blocks/flip-cards/flip-cards.js
Labels: refresh-develop

#752 STERI016-296: Card Block - Primary Card CTA Issues
  blocks/cards/cards.css
  blocks/cards/cards.js
Labels: refresh-develop
