Repository aemsites/stericycle-shared, pull requests merged in 2025-03, with the labels that each got.

#836 STERI016-433: Update radio button styling
  blocks/form/form.css
  blocks/header/nav.css
  blocks/hero-banner/hero-banner.css
Labels: refresh-develop

#840 STERI016-314: Flip Card Tiles - Allow author to choose different CTA button variations(Bugfix)
  blocks/flip-cards/flip-cards.js
Labels: refresh-develop

#846 STERI016-450: Fix offerbox three column layout
  blocks/offer-box/offer-box.css
Labels: refresh-develop

#849 Steri016 356: [Regression] clickable-columns button-container
  blocks/clickable-columns/clickable-columns.css
Labels: refresh-develop

#851 STERI016-462: Fix quote and simple cta layout issues
  blocks/quote/quote.css
  blocks/simple-cta/simple-cta.css
  templates/service-location-page/service-location-page.js
Labels: refresh-develop

#844 STERI016-89: Fix scroll issue with alert banner
  blocks/header/nav.css
  blocks/header/utils.js
Labels: refresh-develop

#852 Steri016 462 flip cards ch
  blocks/header/nav.css
  blocks/simple-cta/simple-cta.css
  styles/styles.css
  templates/service-location-page/service-location-page.css
  templates/service-location-page/service-location-page.js
Labels: refresh-develop

#845 STERI016-436: Add lists support to hero banner
  blocks/hero-banner/hero-banner.css
Labels: refresh-develop

#850 STERI016-451: Alignment Issues - Why Choose Shred-it &
  blocks/columns/default.css
  styles/styles.css
Labels: refresh-develop

#848 STERI016-443: Flip card Block - Missing Title on Flip Card Block with External Destination Link
  blocks/flip-cards/flip-cards.js
Labels: refresh-develop

#853 STERI016-454: Fix modal form and toggle button display issue.
  blocks/form/form.js
Labels: refresh-develop

#847 STERI016-413: [Regression] Cards - button not rendering correctly
  blocks/cards/cards.css
  blocks/cards/cards.js
  blocks/cards/utils.js
  scripts/aem.js
  styles/styles.css
Labels: refresh-develop

#855 STERI016-462: Update CTA styling
  templates/service-location-page/service-location-page.js
Labels: refresh-develop

#856 STERI016-355: [Regression] handle problematic utility classes inherited from main code branch(Bugfix)
  styles/styles.css
Labels: refresh-develop

#859 STERI016-469: Refactor banner with white bg
  blocks/cards/cards.css
  templates/service-location-page-2/service-location-page-2.css
  templates/service-location-page-2/service-location-page-2.js
Labels: refresh-develop

#860 STERI016-460: Update header cta height
  blocks/header/alt-2-nav.css
Labels: refresh-develop

#861 STERI016-452: Update gray color token
  blocks/cards/cards.css
  blocks/footer/footer.css
  styles/styles.css
Labels: refresh-develop

#864 Integrate clarity tracking
  scripts/delayed.js
  scripts/martech.js
Labels: analytics

#863 STERI016-447: Form - Button Toggle Rendering + Privacy Policy Link - Component Revamp
  blocks/form/form.css
  blocks/form/form.js
Labels: refresh-develop

#867 Steri016 487 fix typos
  templates/service-location-page-2/service-location-page-2.js
  templates/service-location-page/service-location-page.js
Labels: refresh-develop

#868 STERI016-489: Update text truncation for flip cards
  blocks/flip-cards/flip-cards.css
  blocks/simple-cta/simple-cta.css
  templates/service-location-page/service-location-page.css
Labels: refresh-develop

#869 no-ref: Fix cards spacing issue
  blocks/cards/cards.css
  templates/service-location-page-2/service-location-page-2.css
Labels: refresh-develop

#870 STERI016-488: Fix header close event action
  blocks/header/utils.js
Labels: refresh-develop

#871 Steri016 494
  blocks/header/nav.js
  scripts/scripts.js
  styles/styles.css
Labels: refresh-develop

#872 Steri016 494
  styles/styles.css
Labels: refresh-develop

#874 Update form styles: change label color to primary and adjust input bo…
  blocks/form/components/radio/radio.css
  blocks/form/form.css
Labels: refresh-develop

#873 STERI016-450: Offer box - Cards Rendering Issues
  blocks/offer-box/offer-box.css
  blocks/offer-box/offer-box.js
  blocks/offer-box/utils.js
Labels: refresh-develop

#876 Steri016 450 fixes
  blocks/offer-box/offer-box.css
Labels: refresh-develop

#808 Add sitemap generation workflow
  .eslintignore
  .github/workflows/fetch-external-hreflangs.yml
  .github/workflows/generate-sitemap.yml
  tools/sitemap-generation/.gitignore
  tools/sitemap-generation/fetch-external-hreflangs.js
  tools/sitemap-generation/generate-sitemap.js
  tools/sitemap-generation/hreflangs.map.json
  tools/sitemap-generation/index.js
  tools/sitemap-generation/package-lock.json
  tools/sitemap-generation/package.json
Labels: SEO
